
package com.example.demo.client.xiecheng;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;
import javax.xml.namespace.QName;
import com.example.demo.bean.InfoListType;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-09T13:12:12.873+08:00
 * Generated source version: 3.3.2
 *
 */
public final class XiechengImplPortImpl_XiechengImplPortImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://a.other.com/", "XiechengImplPortImplService");

    private XiechengImplPortImpl_XiechengImplPortImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = XiechengImplPortImplService.WSDL_LOCATION;

        XiechengImplPortImplService ss = new XiechengImplPortImplService(wsdlURL, SERVICE_NAME);
        XiechengImplPortImpl port = ss.getXiechengImplPortImplPort();

        {
        System.out.println("Invoking getXiechengData...");
        InfoListType _getXiechengData__return = port.getXiechengData();
        System.out.println("getXiechengData.result=" + _getXiechengData__return);
        }

        System.exit(0);
    }

}
