package com.example.demo.client.xiecheng;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-09T13:12:12.976+08:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "XiechengImplPortImplService",
                  wsdlLocation = "http://192.168.1.112:8001/service/XiechengService?wsdl",
                  targetNamespace = "http://a.other.com/")
public class XiechengImplPortImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://a.other.com/", "XiechengImplPortImplService");
    public final static QName XiechengImplPortImplPort = new QName("http://a.other.com/", "XiechengImplPortImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.112:8001/service/XiechengService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(XiechengImplPortImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8001/service/XiechengService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public XiechengImplPortImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XiechengImplPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XiechengImplPortImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public XiechengImplPortImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public XiechengImplPortImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public XiechengImplPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns XiechengImplPortImpl
     */
    @WebEndpoint(name = "XiechengImplPortImplPort")
    public XiechengImplPortImpl getXiechengImplPortImplPort() {
        return super.getPort(XiechengImplPortImplPort, XiechengImplPortImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XiechengImplPortImpl
     */
    @WebEndpoint(name = "XiechengImplPortImplPort")
    public XiechengImplPortImpl getXiechengImplPortImplPort(WebServiceFeature... features) {
        return super.getPort(XiechengImplPortImplPort, XiechengImplPortImpl.class, features);
    }

}
