package com.example.demo.client.xiecheng;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.example.demo.bean.InfoListType;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-09T13:12:12.953+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://a.other.com/", name = "XiechengImplPortImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface XiechengImplPortImpl {

    @WebMethod
    @Action(input = "http://a.other.com/XiechengImplPortImpl/getXiechengDataRequest", output = "http://a.other.com/XiechengImplPortImpl/getXiechengDataResponse")
    @RequestWrapper(localName = "getXiechengData", targetNamespace = "http://a.other.com/", className = "com.other.a.GetXiechengData")
    @ResponseWrapper(localName = "getXiechengDataResponse", targetNamespace = "http://a.other.com/", className = "com.other.a.GetXiechengDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    InfoListType getXiechengData()
;
}
