import com.TuniuImplPortImpl;
import config.Config;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-08T16:23:29.732+08:00
 * Generated source version: 3.3.2
 */

public class Main {

    protected Main() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new TuniuImplPortImpl();
        String address = "http://" + Config.serviceIp + ":8000/service/TuniuService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new Main();
        System.out.println("Server ready...");
    }
}
