package com.example.demo.client.qunar.hello.examples.spyne;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.example.demo.client.qunar.project.*;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-14T20:39:12.574+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "spyne.examples.hello", name = "Application")
@XmlSeeAlso({ObjectFactory.class, ObjectFactory.class})
public interface Application {

    @WebMethod(action = "getTicketsData")
    @RequestWrapper(localName = "getTicketsData", targetNamespace = "spyne.examples.hello", className = "hello.examples.spyne.GetTicketsData")
    @ResponseWrapper(localName = "getTicketsDataResponse", targetNamespace = "spyne.examples.hello", className = "hello.examples.spyne.GetTicketsDataResponse")
    @WebResult(name = "getTicketsDataResult", targetNamespace = "spyne.examples.hello")
    public TicketArray getTicketsData(

        @WebParam(name = "city", targetNamespace = "spyne.examples.hello")
        java.lang.String city
    );
}
