package com.example.demo.client.qunar.hello.examples.spyne;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-14T20:39:12.592+08:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "QunarService",
                  wsdlLocation = "http://192.168.1.111:8000/?wsdl",
                  targetNamespace = "spyne.examples.hello")
public class QunarService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("spyne.examples.hello", "QunarService");
    public final static QName Application = new QName("spyne.examples.hello", "Application");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.111:8000/?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QunarService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.111:8000/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QunarService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QunarService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QunarService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public QunarService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QunarService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QunarService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication() {
        return super.getPort(Application, Application.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication(WebServiceFeature... features) {
        return super.getPort(Application, Application.class, features);
    }

}
