package com;

import config.Config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-08T16:23:29.749+08:00
 * Generated source version: 3.3.2
 */
@WebServiceClient(name = "TuniuImplService",
        wsdlLocation = "http://" + Config.serviceIp + ":8000/service/TuniuService?wsdl",
        targetNamespace = "http://service/")
public class TuniuImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service/", "TuniuImplService");
    public final static QName TuniuImplPort = new QName("http://service/", "TuniuImplPort");

    static {
        URL url = null;
        try {
            url = new URL("http://" + Config.serviceIp + ":8000/service/TuniuService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TuniuImplService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://" + Config.serviceIp + ":8000/service/TuniuService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TuniuImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TuniuImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TuniuImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TuniuImplService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TuniuImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TuniuImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns Tuniu
     */
    @WebEndpoint(name = "TuniuImplPort")
    public Tuniu getTuniuImplPort() {
        return super.getPort(TuniuImplPort, Tuniu.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns Tuniu
     */
    @WebEndpoint(name = "TuniuImplPort")
    public Tuniu getTuniuImplPort(WebServiceFeature... features) {
        return super.getPort(TuniuImplPort, Tuniu.class, features);
    }

}
