package com.other.a;

import com.InfoListType;
import com.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-09T12:57:42.038+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://other.com/", name = "XiechengImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface XiechengImpl {

    @WebMethod
    @Action(input = "http://other.com/XiechengImpl/getXiechengDataRequest", output = "http://other.com/XiechengImpl/getXiechengDataResponse")
    @RequestWrapper(localName = "getXiechengData", targetNamespace = "http://other.com/", className = "com.other.a.GetXiechengData")
    @ResponseWrapper(localName = "getXiechengDataResponse", targetNamespace = "http://other.com/", className = "com.other.a.GetXiechengDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    InfoListType getXiechengData();
}
