
package com.other.a;

import config.Config;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-09T12:57:42.096+08:00
 * Generated source version: 3.3.2
 */

public class XiechengImpl_XiechengImplPort_Server {

    public XiechengImpl_XiechengImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new XiechengImplPortImpl();
        String address = "http://" + Config.serviceIp + ":8001/service/XiechengService";
        Endpoint.publish(address, implementor);
    }
}
