package com.other.a;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-09T12:57:42.107+08:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "XiechengImplService",
                  wsdlLocation = "http://localhost:8001/service/XiechengService?wsdl",
                  targetNamespace = "http://other.com/")
public class XiechengImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://other.com/", "XiechengImplService");
    public final static QName XiechengImplPort = new QName("http://other.com/", "XiechengImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8001/service/XiechengService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(XiechengImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8001/service/XiechengService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public XiechengImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XiechengImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XiechengImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public XiechengImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public XiechengImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public XiechengImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns XiechengImpl
     */
    @WebEndpoint(name = "XiechengImplPort")
    public XiechengImpl getXiechengImplPort() {
        return super.getPort(XiechengImplPort, XiechengImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XiechengImpl
     */
    @WebEndpoint(name = "XiechengImplPort")
    public XiechengImpl getXiechengImplPort(WebServiceFeature... features) {
        return super.getPort(XiechengImplPort, XiechengImpl.class, features);
    }

}
