package com.example.demo.client.tuniu;

import com.example.demo.bean.InfoListType;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-08T16:39:33.082+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://com/", name = "TuniuImplPortImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface TuniuImplPortImpl {

    @WebMethod
    @Action(input = "http://com/TuniuImplPortImpl/getTuniuDataRequest", output = "http://com/TuniuImplPortImpl/getTuniuDataResponse")
    @RequestWrapper(localName = "getTuniuData", targetNamespace = "http://com/", className = "com.GetTuniuData")
    @ResponseWrapper(localName = "getTuniuDataResponse", targetNamespace = "http://com/", className = "com.GetTuniuDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    InfoListType getTuniuData()
;
}
