
package com.example.demo.client.tuniu;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.example.demo.bean.InfoListType;

import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-08T16:39:33.028+08:00
 * Generated source version: 3.3.2
 *
 */
public final class TuniuImplPortImpl_TuniuImplPortImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://com/", "TuniuImplPortImplService");

    private TuniuImplPortImpl_TuniuImplPortImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TuniuImplPortImplService.WSDL_LOCATION;

        TuniuImplPortImplService ss = new TuniuImplPortImplService(wsdlURL, SERVICE_NAME);
        TuniuImplPortImpl port = ss.getTuniuImplPortImplPort();

        {
        System.out.println("Invoking getTuniuData...");
        InfoListType _getTuniuData__return = port.getTuniuData();
        System.out.println("getTuniuData.result=" + _getTuniuData__return);


        }

        System.exit(0);
    }

}
